import type { Metadata } from 'next'
import './report.css'

export const metadata: Metadata = {
  title: 'DealNector Valuation Report',
  description: 'Institutional valuation report generated by DealNector',
}

/**
 * Report route layout — this is a NESTED layout, so it must NOT
 * declare its own html/body (those come from the root layout).
 * It only scopes report.css and wraps children in a neutral
 * container so the Providers from the root still work (session,
 * news data, etc.) and the root globals.css dark theme is
 * overridden by our print-first report.css cascade.
 */
export default function ReportLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <main className="dn-report-root">{children}</main>
}
