/**
 * Keyword dictionaries for matching Google News results to our domain.
 *
 * All keys are matched case-insensitively against the combined
 * title+description text of each news item.
 */

// ─── Industry-level keywords (broad) ───────────────────────────────

export const INDUSTRY_KEYWORDS: Record<'solar' | 'td', string[]> = {
  solar: [
    'solar',
    'photovoltaic',
    'pv module',
    'pv cell',
    'solar cell',
    'solar module',
    'solar panel',
    'renewable energy',
    'rooftop solar',
    'solar ipp',
    'almm',
    'polysilicon',
    'wafer',
    'topcon',
    'heterojunction',
    'bifacial',
  ],
  td: [
    'transmission',
    'distribution',
    'transformer',
    'power transformer',
    'distribution transformer',
    'substation',
    'switchgear',
    'smart meter',
    'power grid',
    'cable',
    'hvdc',
    'conductor',
    'acsr',
    'rdss',
    'ami',
    'discom',
  ],
}

// ─── Value-chain segment keywords (matches CHAIN ids) ─────────────
// Keys correspond to the `id` field in `src/lib/data/chain.ts`.

export const CHAIN_KEYWORDS: Record<string, string[]> = {
  solar_modules: ['solar module', 'pv module', 'solar panel', 'module manufacturing'],
  solar_cells: ['solar cell', 'topcon', 'perc', 'heterojunction', 'hjt'],
  wafers: ['silicon wafer', 'wafer manufacturing', 'm10 wafer', 'g12 wafer'],
  polysilicon: ['polysilicon', 'poly silicon'],
  pv_glass: ['pv glass', 'solar glass', 'tempered solar glass'],
  encapsulants: ['eva encapsulant', 'poe encapsulant', 'encapsulant'],
  backsheet: ['backsheet', 'back sheet'],
  al_frame: ['aluminum frame', 'aluminium frame', 'module frame'],
  junction_box: ['junction box'],
  silver_paste: ['silver paste'],
  bus_ribbon: ['bus ribbon', 'interconnect ribbon'],
  inverters: ['solar inverter', 'string inverter', 'central inverter', 'micro-inverter'],
  mounting: ['mounting structure', 'solar mounting', 'tracker', 'fixed-tilt'],
  power_transformers: [
    'power transformer',
    'ehv transformer',
    '400kv',
    '765kv',
    '220kv',
    'hvdc',
  ],
  dist_transformers: ['distribution transformer', 'dtr'],
  acsr_conductors: ['acsr', 'conductor', 'transmission line'],
  htls: ['htls', 'high temperature low sag'],
  hv_cables: ['hv cable', 'xlpe cable', 'underground cable', 'ehv cable'],
  smart_meters: ['smart meter', 'rdss', 'ami', 'advanced metering'],
  switchgear: ['switchgear', 'gis', 'gas insulated', 'circuit breaker'],
  bess: ['bess', 'battery storage', 'energy storage', 'lithium-ion storage'],
  ems: ['ems ', 'scada', 'grid management'],
}

// ─── Policy / regulatory keywords ──────────────────────────────────

export const POLICY_KEYWORDS = [
  'pli scheme',
  'pli solar',
  'almm',
  'rdss',
  'basic customs duty',
  'bcd',
  'anti-dumping',
  'mnre',
  'seci',
  'nsm',
  'national solar mission',
  'green energy corridor',
  'gec',
  'cbam',
  'ipef',
  'renewable purchase obligation',
  'rpo',
  'pmsy',
  'pm kusum',
  'pm-kusum',
  'pm surya ghar',
]

// ─── Sentiment keywords (used by impact estimator) ─────────────────

export const POSITIVE_KEYWORDS = [
  'growth',
  'profit',
  'surges',
  'surge',
  'record',
  'rally',
  'gains',
  'beat',
  'beats',
  'upgrade',
  'wins',
  'awarded',
  'launches',
  'order book',
  'order win',
  'order',
  'contract',
  'capacity expansion',
  'commissioning',
  'commissioned',
  'acquisition',
  'acquires',
  'merger',
  'subsidy',
  'incentive',
  'approved',
  'approval',
  'pli beneficiary',
  'boost',
  'ramp-up',
  'strong demand',
  'strong quarter',
  'revenue jump',
  'breakthrough',
  'ipo',
  'listing',
  'debut',
  'milestone',
  'green light',
  'exemption',
  'tax holiday',
]

export const NEGATIVE_KEYWORDS = [
  'loss',
  'losses',
  'decline',
  'declines',
  'falls',
  'fell',
  'probe',
  'investigation',
  'fraud',
  'downgrade',
  'default',
  'defaulted',
  'layoff',
  'layoffs',
  'shutdown',
  'cancelled',
  'cancellation',
  'delay',
  'delayed',
  'penalty',
  'fine',
  'slump',
  'crash',
  'warning',
  'recall',
  'import duty',
  'anti-dumping',
  'dumping',
  'tariff hike',
  'raid',
  'arrest',
  'litigation',
  'bankruptcy',
  'insolvency',
  'nclt',
  'downgraded',
  'weak demand',
  'margin pressure',
  'cost overrun',
  'fire',
  'accident',
  'strike',
  'protest',
  'blocked',
  'suspended',
]

// ─── Ticker → alias strings used for company detection ────────────
// The key is the NSE ticker from COMPANIES. The values are additional
// strings beyond the full company name that should count as a match.

export const COMPANY_ALIASES: Record<string, string[]> = {
  WAAREEENS: ['waaree energies', 'waaree'],
  WAAREERTL: ['waaree renewable', 'waaree rtl'],
  PREMIENRG: ['premier energies'],
  BORORENEW: ['borosil renewables', 'borosil'],
  WEBELSOLAR: ['websol'],
  STERLINWIL: ['sterling wilson', 'shapoorji pallonji solar'],
  POLYCAB: ['polycab'],
  KEI: ['kei industries'],
  FNXCABLE: ['finolex cables'],
  UNIVCABLES: ['universal cables'],
  APARINDS: ['apar industries'],
  KEC: ['kec international'],
  SIEMENS: ['siemens india', 'siemens limited'],
  ABB: ['abb india'],
  BHEL: ['bhel'],
  CGPOWER: ['cg power'],
  VOLTAMP: ['voltamp'],
  INDOTECH: ['indo tech', 'indo tech transformers'],
  SHILCTECH: ['shilchar'],
  HITACHIEN: ['hitachi energy'],
  GENUSPAPER: ['genus power'],
  HPL: ['hpl electric'],
  ADANIENSOL: ['adani energy solutions', 'adani transmission'],
  AMARARAJA: ['amara raja'],
  EXIDEIND: ['exide industries'],
  HAVELLS: ['havells'],
  TECHNOE: ['techno electric'],
  TDPOWERSYS: ['td power', 'tdpower'],
  POWERMECH: ['power mech'],
  PRAJIND: ['praj industries'],
  CESC: ['cesc limited', 'rp sanjiv goenka'],
  INSOLATION: ['insolation energy', 'ina solar'],
  KPIGREEN: ['kpi green'],
  SWELECTES: ['swelect energy'],
  UJAAS: ['ujaas energy'],
  SURANASOL: ['surana solar'],
  ZODIAENERGY: ['zodiac energy'],
  ALPEXSOLAR: ['alpex solar'],
  ADANIGREEN: ['adani green', 'adani green energy'],
  JSWENERGY: ['jsw energy'],
  NTPC: ['ntpc limited'],
  TORNTPOWER: ['torrent power'],
  INOXGREEN: ['inox green'],
  ORIENTGREEN: ['orient green power'],
  PENNARIND: ['pennar industries'],
  RAJRATAN: ['rajratan global'],
  TARIL: ['transformers and rectifiers', 'tari'],
  GETANDEL: ['ge vernova', 'ge t&d'],
  KIRILELEC: ['kirloskar electric'],
  EMCO: ['emco limited', 'emco transformers'],
  STRTECH: ['sterlite technologies'],
  DPIL: ['diamond power'],
  SKIPPER: ['skipper limited'],
  CORDSCAB: ['cords cable'],
  PARACOM: ['paramount communications'],
  VINDHYATEL: ['vindhya telelinks'],
  HBLPOWER: ['hbl power'],
  POWERGRID: ['power grid corporation', 'powergrid'],
  INDIGRID: ['indigrid'],
}
