import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { isAdminOrSubadmin } from '@/lib/auth-helpers'
import sql from '@/lib/db'
import { ensureSchema } from '@/lib/db/ensure-schema'
import atlas from '@/data/atlas-seed.json'

/**
 * POST /api/admin/seed-atlas
 *
 * Admin-only. Reads src/data/atlas-seed.json (generated by
 * scripts/parse-atlas.mjs from the Waaree Industry Value Chain Atlas PDF)
 * and upserts:
 *   - industries row per industry
 *   - industry_chain_nodes row per stage (with description)
 *   - industry_chain_companies rows per company (status + exchange + ticker + role)
 *
 * Idempotent: running twice refreshes labels/descriptions without
 * duplicating rows.
 *
 * Optional body: { industries?: string[] } — limit seeding to a subset
 * by industry id (e.g. ["solar_pv_and_renewable_energy"]).
 */

interface AtlasCompany {
  name: string
  status: string
  exchange: string
  ticker: string
  role: string
}
interface AtlasStage {
  id: string
  name: string
  description: string
  companies: AtlasCompany[]
}
interface AtlasIndustry {
  id: string
  code: string
  label: string
  description: string
  icon: string
  stages: AtlasStage[]
}
interface AtlasSeed {
  industries: AtlasIndustry[]
  generatedAt: string
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  const role = (session?.user as { role?: string } | undefined)?.role
  if (!session?.user || !isAdminOrSubadmin(role)) {
    return NextResponse.json({ ok: false, error: 'Forbidden' }, { status: 403 })
  }

  let limit: Set<string> | null = null
  try {
    const body = await req.json().catch(() => ({}))
    if (Array.isArray(body.industries) && body.industries.length > 0) {
      limit = new Set(body.industries.map(String))
    }
  } catch {
    /* optional body */
  }

  try {
    await ensureSchema()
    const seed = atlas as AtlasSeed
    const email = (session.user as { email?: string }).email ?? null

    let industriesUpserted = 0
    let stagesUpserted = 0
    let companiesUpserted = 0

    for (const ind of seed.industries) {
      if (limit && !limit.has(ind.id)) continue

      // industries row — atlas-seeded entries are removable by admins, so
      // we deliberately set is_builtin=FALSE. The only truly built-in
      // industries are 'solar' and 'td' seeded in ensureSchema().
      // Use COALESCE on update so existing rows keep their is_builtin flag
      // (protects 'solar'/'td' if they ever land in the atlas).
      await sql`
        INSERT INTO industries (id, label, icon, description, is_builtin, added_by)
        VALUES (${ind.id}, ${ind.label}, ${ind.icon}, ${ind.description}, FALSE, ${email})
        ON CONFLICT (id) DO UPDATE
          SET label = EXCLUDED.label,
              icon = EXCLUDED.icon,
              description = EXCLUDED.description,
              updated_at = NOW()
      `
      industriesUpserted++

      for (const stg of ind.stages) {
        const nodeId = `${ind.id}__${stg.id}`.slice(0, 80)
        // Use the stage name as BOTH name + cat so the existing value-chain
        // merge logic (cat is the parent group) continues to work.
        await sql`
          INSERT INTO industry_chain_nodes (
            id, industry_id, name, cat, flag, description
          )
          VALUES (
            ${nodeId}, ${ind.id}, ${stg.name}, ${stg.name}, 'medium',
            ${stg.description || null}
          )
          ON CONFLICT (id) DO UPDATE
            SET name = EXCLUDED.name,
                cat = EXCLUDED.cat,
                description = EXCLUDED.description
        `
        stagesUpserted++

        for (const co of stg.companies) {
          const name = co.name.slice(0, 240)
          await sql`
            INSERT INTO industry_chain_companies (
              industry_id, stage_id, name, status, exchange, ticker, role
            )
            VALUES (
              ${ind.id}, ${nodeId}, ${name}, ${co.status},
              ${co.exchange || null}, ${co.ticker || null}, ${co.role || null}
            )
            ON CONFLICT (industry_id, stage_id, name) DO UPDATE
              SET status = EXCLUDED.status,
                  exchange = EXCLUDED.exchange,
                  ticker = EXCLUDED.ticker,
                  role = EXCLUDED.role
          `
          companiesUpserted++
        }
      }
    }

    return NextResponse.json({
      ok: true,
      industries: industriesUpserted,
      stages: stagesUpserted,
      companies: companiesUpserted,
      generatedAt: seed.generatedAt,
    })
  } catch (err) {
    return NextResponse.json(
      { ok: false, error: err instanceof Error ? err.message : String(err) },
      { status: 500 }
    )
  }
}

/** GET returns the seed manifest counts so the admin UI can preview. */
export async function GET() {
  const session = await getServerSession(authOptions)
  const role = (session?.user as { role?: string } | undefined)?.role
  if (!session?.user || !isAdminOrSubadmin(role)) {
    return NextResponse.json({ ok: false, error: 'Forbidden' }, { status: 403 })
  }
  const seed = atlas as AtlasSeed
  const summary = seed.industries.map((i) => ({
    id: i.id,
    code: i.code,
    label: i.label,
    icon: i.icon,
    stages: i.stages.length,
    companies: i.stages.reduce((a, s) => a + s.companies.length, 0),
  }))
  return NextResponse.json({
    ok: true,
    generatedAt: seed.generatedAt,
    industries: summary,
    totalCompanies: summary.reduce((a, x) => a + x.companies, 0),
  })
}
